{{- if .Values.controller.enabled -}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "democratic-csi.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "democratic-csi.name" . }}
    helm.sh/chart: {{ include "democratic-csi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/csi-role: "controller"
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "democratic-csi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/driver-config-secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "democratic-csi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/csi-role: "controller"
    spec:
      {{- if .Values.controller.rbac.enabled }}
      serviceAccount: {{ include "democratic-csi.fullname" . }}-controller-sa
      {{- end }}
      containers:
      {{- if .Values.controller.externalProvisioner.enabled }}
      # https://github.com/kubernetes-csi/external-provisioner
      - name: external-provisioner
        image: {{ .Values.controller.externalProvisioner.image }}
        args:
        - --v=5
        - --enable-leader-election
        - --leader-election-type=leases
        - --timeout=90s
        - --worker-threads=10
        - --csi-address=/csi-data/csi.sock
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      {{- end }}

      {{- if .Values.controller.externalResizer.enabled }}
      # https://github.com/kubernetes-csi/external-resizer
      - name: external-resizer
        image: {{ .Values.controller.externalResizer.image }}
        args:
        - --v=5
        - --leader-election
        - --csi-address=/csi-data/csi.sock
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      {{- end }}

      {{- if .Values.controller.externalSnapshotter.enabled }}
      # https://github.com/kubernetes-csi/external-snapshotte
      # beware upgrading version:
      #  - https://github.com/rook/rook/issues/4178
      #  - https://github.com/kubernetes-csi/external-snapshotter/issues/147#issuecomment-513664310
      - name: external-snapshotter
        {{- if .Values.controller.externalSnapshotter.image }}
        image: {{ .Values.controller.externalSnapshotter.image }}        
        {{- else }}
        {{- if semverCompare ">=1.17.0-0" .Capabilities.KubeVersion.GitVersion }}
        image: quay.io/k8scsi/csi-snapshotter:v2.1.0
        {{- else }}
        image: quay.io/k8scsi/csi-snapshotter:v1.2.2
        {{- end }}
        {{- end }}

        args:
        - --v=5
        - --leader-election
        - --csi-address=/csi-data/csi.sock
        - --timeout=90s
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      {{- end }}

      {{- if .Values.controller.livenessProbe.enabled }}
      # https://github.com/kubernetes-csi/livenessprobe
      - name: livenessprobe
        image: {{ .Values.controller.livenessProbe.image }}
        args:
        - --v=5
        - --csi-address=/csi-data/csi.sock
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      {{- end }}

      {{- if .Values.controller.driver.enabled }}
      - name: csi-driver
        image: {{ .Values.controller.driver.image }}
        args:
        - --csi-version={{ .Values.csiDriver.version }}
        - --csi-name={{ .Values.csiDriver.name }}
        - --driver-config-file=/config/driver-config-file.yaml
        - --log-level={{ .Values.controller.driver.logLevel }}
        - --csi-mode=controller
        - --server-socket=/csi-data/csi.sock
        imagePullPolicy: Always

        {{- if .Values.controller.livenessProbe.enabled }}
        # Defining port which will be used to GET plugin health status
        # 9808 is default, but can be changed.
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        # The probe
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 60
        {{- end }}
        volumeMounts:
        - name: socket-dir
          mountPath: /csi-data
        - name: config
          mountPath: /config
      {{- end }}
          
      volumes:
      - name: socket-dir
        emptyDir:
      - name: config
        secret:
          secretName: {{ include "democratic-csi.fullname" . }}-driver-config
{{- end }}
