{{- if and .Values.controller.enabled (eq .Values.controller.strategy "deployment") -}}
{{- $controllerStrategy := "deployment" -}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "democratic-csi.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "democratic-csi.name" . }}
    helm.sh/chart: {{ include "democratic-csi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/csi-role: "controller"
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "democratic-csi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/driver-config-secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "democratic-csi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/csi-role: "controller"
    spec:
      {{- if .Values.controller.rbac.enabled }}
      serviceAccount: {{ include "democratic-csi.fullname" . }}-controller-sa
      {{- end }}
      hostNetwork: {{ .Values.controller.hostNetwork }}
      hostIPC: {{ .Values.controller.hostIPC }}
      containers:

      {{- if and .Values.controller.externalProvisioner.enabled (eq .Values.controller.strategy $controllerStrategy) }}
{{ include "democratic-csi.external-provisioner-container" . | indent 6 }}
      {{- end }}

      {{- if and .Values.controller.externalResizer.enabled (eq .Values.controller.strategy $controllerStrategy) }}
{{ include "democratic-csi.external-resizer-container" . | indent 6 }}
      {{- end }}

      {{- if and .Values.controller.externalSnapshotter.enabled (eq .Values.controller.strategy $controllerStrategy) }}
{{ include "democratic-csi.external-snapshotter-container" . | indent 6 }}
      {{- end }}

      {{- if .Values.controller.livenessProbe.enabled }}
{{ include "democratic-csi.livenessprobe-container" . | indent 6 }}
        image: {{ .Values.controller.livenessProbe.image }}
      {{- end }}

      {{- if .Values.controller.driver.enabled }}
      - name: csi-driver
        image: {{ .Values.controller.driver.image }}
        {{- if .Values.controller.driver.lifecycle }}
        lifecycle:
{{ toYaml .Values.controller.driver.lifecycle | indent 10 }}
        {{- end }}
        args:
        - --csi-version={{ .Values.csiDriver.version }}
        - --csi-name={{ .Values.csiDriver.name }}
        - --driver-config-file=/config/driver-config-file.yaml
        - --log-level={{ .Values.controller.driver.logLevel }}
        - --csi-mode=controller
        - --server-socket=/csi-data/csi.sock
        imagePullPolicy: Always

        # https://github.com/kubernetes-csi/livenessprobe/issues/82
        {{- if .Values.controller.livenessProbe.enabled }}
        # Defining port which will be used to GET plugin health status
        # 9808 is default, but can be changed.
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        # The probe
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 60
        {{- end }}
        volumeMounts:
        - name: socket-dir
          mountPath: /csi-data
        - name: config
          mountPath: /config
{{- if .Values.controller.driver.extraVolumeMounts }}
{{ toYaml .Values.controller.driver.extraVolumeMounts | indent 8 }}
{{- end }}
      {{- end }}
          
      volumes:
      - name: socket-dir
        emptyDir:
      - name: config
        secret:
          secretName: {{ include "democratic-csi.fullname" . }}-driver-config
{{- if .Values.controller.extraVolumes }}
{{ toYaml .Values.controller.extraVolumes | indent 6 }}
{{- end }}

{{- end }}
