# Default values for snapshot-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  enabled: true

controller:
  enabled: true
  replicaCount: 3
  image:
    repository: k8s.gcr.io/sig-storage/snapshot-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v6.0.1

  args:
  - "--v=5"
  - "--leader-election=true"
  - "--enable-distributed-snapshotting"
  extraArgs: []

validatingWebhook:
  enabled: false
  replicaCount: 3
  image:
    repository: k8s.gcr.io/sig-storage/snapshot-validation-webhook
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v5.0.1

